const START_FETCH = 'auth/START_FETCH';
const END_FETCH = 'auth/END_FETCH';
const END_ERROR = 'auth/END_ERROR';
const UPDATE_PROFILE = 'auth/UPDATE_PROFILE';
const UPDATE_USER = 'auth/UPDATE_USER';
const API_CALL = 'auth/API_CALL';
const CHANGE_LANGUAGE = 'auth/CHANGE_LANGUAGE';
const MESSAGE = 'auth/MESSAGE';
const CLEAR = 'auth/CLEAR';

export default {
  START_FETCH,
  END_FETCH,
  END_ERROR,
  UPDATE_PROFILE,
  UPDATE_USER,
  API_CALL,
  CHANGE_LANGUAGE,
  MESSAGE,
  CLEAR,
};
